version: '0'
services:
  nginx:
    image: nginx
  mariadb:
    image: mariadb
    networks:
      - networkName
    volumes:
      - db_vol:containerPath:ro
  wordpress:
    depends_on:
      - mariadb
    image: wordpress
    networks:
      - networkName
    volumes:
      - wp_vol:containerPath
    ports:
      - '8080:80'
networks:

volumes:
env_file:
