version: '3.8'
name: inception

services:
  mariadb:
    build: ./requirements/mariadb
    image: mariadb
    container_name: mariadb
    ports:
      - '3306:3306'
    volumes:
      - db_vol:/var/lib/mysql
    env_file:
      - .env

volumes:
  db_vol:
