version: "3.8"
name: inception

services:
  mariadb:
    build: ./requirements/mariadb
    image: mariadb:1.0
    container_name: mariadb
    ports:
      - "3306"
    networks:
      - my_network
    volumes:
      - db_vol:/var/lib/mysql
    env_file:
      - .env
    restart: always

  wordpress:
    build: ./requirements/wordpress
    image: wordpress:1.0
    container_name: wordpress
    ports:
      - "9000"
    networks:
      - my_network
    volumes:
      - wp_vol:/var/www/html
    depends_on:
      - mariadb
    env_file:
      - .env
    restart: always

  nginx:
    build: ./requirements/nginx
    image: nginx:1.0
    container_name: nginx
    ports:
      - "443:443"
    networks:
      - my_network
    volumes:
      - wp_vol:/var/www/html
    depends_on:
      - mariadb
      - wordpress
    restart: always

networks:
  my_network:
    driver: bridge

volumes:
  db_vol:
    driver: local
    driver_opts:
      o: bind
      type: none
      # device: ./data/mariadb
      device: /Users/hyobicho/42projects/inception/srcs/data/mariadb
      # device: /home/hyobicho/data/mariadb
  wp_vol:
    driver: local
    driver_opts:
      o: bind
      type: none
      # device: ./data/wordpress
      device: /Users/hyobicho/42projects/inception/srcs/data/wordpress
      # device: /home/hyobicho/data/worpress
